---
- name: Generate Private Key
  shell: 'openssl req -newkey rsa:4096 -nodes -sha256 -keyout {{ registry_name }}.key -x509 -days 365 -out {{ registry_name }}.crt -subj "/C=US/ST=California/L=Seal Beach/O=Boeing/OU=Irvine/CN={{ registry_name }}"'
  args: 
    chdir: '{{ registry_dir }}/certs/'

    #- name: Generate CSR
    #  vars:
    #    owner: redhatter
    #  become: yes
    #  openssl_csr:
    #    path: '{{ registry_dir }}/certs/{{ registry_name }}.csr'
    #    privatekey_path: '{{ registry_dir }}/certs/{{ registry_name }}.key'
    #    country_name: US
    #    state_or_province_name: "{{ state_name }}"
    #    locality_name: "{{ city }}"
    #    organization_name: "{{ organization_name }}"
    #    organizational_unit_name: "{{ organizational_unit }}"
    #    common_name: "{{ registry_name }}"
    #    email_address: "{{ email_address }}"
    #    owner: "{{ owner }}"

    #- name: Generate self-signed certificate
    #  vars:
    #    owner: redhatter
    # become: yes
    #  openssl_certificate:
    #    path: '{{ registry_dir }}/certs/{{ registry_name }}.crt'
    #    csr_path: '{{ registry_dir }}/certs/{{ registry_name }}.csr'
    #    privatekey_path: '{{ registry_dir }}/certs/{{ registry_name }}.key'
    #    provider: selfsigned
    #    owner: "{{ owner }}"

