## Temporarily commented
#- name: Download the ova file 
#    get_url:
#      url: "{{ ova_url }}"
#      dest: "{{ install_dir }}/{{ rhcos_ova }}"
#      validate_certs: no
#    when: skip_ova is not defined

#- name: Deploy the OVF template into the folder
#  vmware_deploy_ovf:
#    hostname: "{{ vcenter.ip }}"
#    username: "{{ vcenter_user }}"
#    password: "{{ vcenter_passwd }}"
#    datacenter: "{{ datacenter }}"
#    datastore: "{{ datastore }}"
#    folder: "{{ folder }}"
#    name: '{{ template_name }}'
#    allow_duplicates: False
#    disk_provisioning: thin
#    networks: "{u'VM Network':u'{{ vcenter_network }}'}"
#    ova: "{{ playbook_dir }}/downloads/{{ template_name }}.ova"
#    power_on: False
#    validate_certs: False
#  when: skip_ova is not defined
  
#- name: Remove the Network Adapter  
#  command: "govc device.remove -vm {{ folder }}/{{ template_name }} ethernet-0"
#  when: skip_ova is not defined

#- name: Update VM options on the template
#  command: "govc vm.change -vm {{ folder }}/{{ template_name }} -latency high -e=disk.EnableUUID=TRUE -e=guestinfo.ignition.config.data.encoding=base64 -e=guestinfo.ignition.config.data=blah"
#  when: skip_ova is not defined      

- name: "Bootstrap base64"
  debug:
    msg: "{{lookup('file', '{{ install_dir }}/append-bootstrap.64')}}"
    verbosity: 1
- name: "Master base64"
  debug:
    msg: "{{lookup('file', '{{ install_dir }}/master.64') }}"
    verbosity: 1
- name: "Worker base64 "
  debug:
    msg: "{{lookup('file', '{{ install_dir }}/worker.64') }}"
    verbosity: 1


- name: Create nodes
  vmware_guest:
    hostname: "{{ vcenter_ip }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_passwd }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    folder: /irvine44
    name: "{{ item.machine_name }}"
    state: "{{ vm_power_state }}"
    template: "{{ template_name }}"
    hardware:
      memory_mb: 16384
      num_cpus: 4
      memory_reservation_lock: True
#    networks:
#    - name: "{{ vcenter_network }}"
#mac: "{{ item.macaddress }}"
    wait_for_ip_address: no
    customvalues:
      - key: guestinfo.ignition.config.data
        value: "{{ lookup('file', '{{ item.ign }}') }}"
      - key: guestinfo.ignition.config.data.encoding
        value: base64
      - key: disk.EnableUUID
        value: "TRUE"
  loop:
    - { machine_name: 'pbootstrap', macaddress: "00:50:56:a4:10:31", ign: "{{ install_dir }}/append-bootstrap.64" }
    - { machine_name: 'pmaster0', macaddress: "00:50:56:a4:10:2b", ign: "{{ install_dir }}/master.64" }
    - { machine_name: 'pmaster1', macaddress: "00:50:56:a4:10:2c", ign: "{{ install_dir }}/master.64" }
    - { machine_name: 'pmaster2', macaddress: "00:50:56:a4:10:2d", ign: "{{ install_dir }}/master.64" }
    - { machine_name: 'pworker0', macaddress: "00:50:56:a4:10:2e", ign: "{{ install_dir }}/worker.64" }
    - { machine_name: 'pworker1', macaddress: "00:50:56:a4:10:2f", ign: "{{ install_dir }}/worker.64" }
    - { machine_name: 'pworker2', macaddress: "00:50:56:a4:10:30", ign: "{{ install_dir }}/worker.64" }      

