---
install_dir: '{{ home_dir }}/irvine44'
ocp_image: rhcos-ocp44
ova_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-4.4.3-x86_64-vmware.ova
rhcos_ova: rhcos-4.4.3-x86_64-vmware.x86_64.ova

home_dir: /home/redhatter
domain_name: greydawn.boeinglabnet.net
cluster_name: irvine44

utility_node: utility44.{{ domain_name }}

merged_secret_path: '{{ install_dir }}/merged_pullsecret.json'
ocp_pull_secret: '{{ install_dir }}/ocp_pullsecret.json'
registry_pull_secret: '{{ install_dir }}/pullsecret_config.json'
LOCAL_REGISTRY: '{{ utility_node }}:5000'
LOCAL_REPOSITORY: ocp4/openshift4
registry_name: '{{ utility_node }}'

pub_key: '{{ install_dir }}/.ssh/id_rsa.pub'
fips_mode: false
vcenter_server: gd-vcsac01.greydawn.boeinglabnet.net
vcenter_user: administrator@vsphere.local
vcenter_passwd: VMwar3!!
datacenter: Greydawn
datastore: DS02
vm_power_state: present
vcenter_ip: '10.126.69.18'
folder: /Greydawn/irvine44
template_name: RHCOS-template
vcenter_network: '10.126.72.0/24'

