vcenter_server: gd-vcsac01.greydawn.boeinglabnet.net
vcenter_user: administrator@vsphere.local
vcenter_passwd: VMwar3!!
datacenter: Greydawn
datastore: DS02
domain_name: greydawn.boeinglabnet.net
cluster_name: dc0-Cluster
vcenter.ip: '10.126.69.18'
